# train setting
img_w: 640
img_h: 480
workers: 32
batch_size: 10
epochs: 40
lr: 0.00001
min_depth: 0.01
max_depth: 10
seed: 12
freeze_backbone: true

save_path_template: "exp/nyud/{module_part}/{activation}"
log_directory_template: "train_logs/nyud/{module_part}/{activation}"

# dataloader setting
dataset: "NYUD"
trainset_path: "dataset/splits/nyud/train.txt"
valset_path: "dataset/splits/nyud/val.txt"

# model weights load setting
pretrained_from: "../checkpoints/relative/latest_epoch_83.pth"
resume: null